# sourceにはパースしたいファイル（.cssや.scssなど）があるディレクトリを指定します。
source: ../develop/

# スタイルガイドを生成するCSSファイルの相対パスを指定します。
css_include:
  - '../release/assets/css/common.css'

# スタイルガイドを出力するディレクトリを指定します。
destination: ../styleguide/

# スタイルガイドのタイトルを指定します。
global_title: Styleguide

# スタイルガイドのテンプレートになるファイルの入ったディレクトリを指定します。
documentation_assets: ./template/

# Hologramのマークダウンの機能（Redcarpe）を拡張するファイルです。
custom_markdown: markdown_renderer.rb
